### PR TITLE
disallow scrolling beyond file contents

### LINKED ISSUE #11: Scrolling beyond file contents
If you press the scroll down key repeatedly, you can scroll over the edge of the file as far as you want. It only works with the scroll key, not the cursor, though, which stops correctly at the end of the file.

The cursor is not moved when scrolling, though, in case this is not intentional this might be a related issue.

### PR DESCRIPTION
**Pull request by florianjacob**
Fixes #11

### CODE REVIEW

**Comment by florianjacob** [comment]
I tried to receive `file_line_length` with

```
let file_length = buffer.data.borrow().to_string().lines().count();
```
as it seems to be accessed in `scribe::cursor`, but that doesn't work from amp as `data` is private.

**Comment by jmacdonald** [comment]
@florianjacob ah, you'll want to use the `Buffer` type's `data` [method](http://jordanmacdonald.ca/rust/scribe/buffer/struct.Buffer.html#method.data) instead. :smile:

**Comment by florianjacob** [comment]
Ah, missed that there is generated documentation for scribe. :smile: 

Now the problem is that `.data()` is a mutable method, but the `&buffer` is not mutable.
Also, I found the `presenters::line_count` private helper function which seems to have the same purpose as what I'm trying to do here with `data().to_string().lines().count()`.

Not sure how to go forward from here.
Maybe this should be shared as a non-mutable method on `scribe::Buffer` to hide the detail how to efficiently compute or even cache the line count of the buffer?

**Comment by jmacdonald** [comment]
@florianjacob good point re: `data()` requiring the buffer reference to be mutable. I've always been divided on that; I'll roll back the caching implementation on that to alleviate the mutability requirement. The tokenizing library is likely to get a performance boost soon with a zero-copy tokenizer implementation, so in all likelihood, caching will be a premature optimization.

I'm also thinking about implementing a `line_count` method directly on `Buffer`. The `lines` iterator doesn't count trailing newlines, and Amp itself [enforces trailing newline characters](https://github.com/jmacdonald/amp/tree/master/src/commands/buffer.rs#L11), so using it is going to be a common "off by one" pitfall for developers.

Let me make these changes and I'll let you know when they're available!

**Comment by jmacdonald** [comment]
Okay, I've removed the mutability requirements and have added a `line_count` method to the `Buffer` type; feel free to give this another go, if you'd like!

**Comment by florianjacob** [comment]
Now the feature itself works as intended, but the test cases fail to compile because they don't set a limit on scroll_down. I start to realize that other scrolling methods besides scroll_down would also need to do a bound check as some of them can also increase the line_offset beyond the limit.

Today I learned: Should have been more test-driven here and started by writing / modifying tests.

My current idea of a solution would be to add the height of the underlying thing the scrollable_region scrolls over as a parameter and then add method to modify the line_offset which does the bound checking in both directions, which is then used by all other methods in scrollable_region instead of directly changing line_offset. What do you think of it? Other thoughts?

**Comment by jmacdonald** [comment]
The `ScrollableRegion` type doesn't know anything about the `Buffer` type (or more generally, any of the content within it) right now. I'd prefer to avoid adding height information relating to an external type; we'd have to update that state manually (likely in methods of the `View` type), or provide the region with a reference to a trait object that provides height information, which in this case, would be a buffer.

Let's update the `View` type's [scroll down method](https://github.com/jmacdonald/amp/tree/master/src/view/mod.rs#L283-L285) instead. The `View` type is already [making use of `Buffer` attributes](https://github.com/jmacdonald/amp/tree/master/src/view/mod.rs#L272), so it feels like a good fit. The other scrolling methods are cursor-based, which already does bounds checking, except for `scroll_up`, so the `scroll_down` method is the only one that needs to check the max value. 

We can add an integration test to the `View` type's `scroll_down` method to make sure that it consults the  buffer's line count before scrolling. In the test environment, the `Terminal` type's height is locked at `10`. If you create a buffer with a line count greater than 5, and call `scroll_down` with a larger value, you should be able to use `visible_region(buf)` to check that the line offset is set to the correct maximum.

**Comment by jmacdonald** [comment]
I've implemented this via 56fc841a86d9f7f3e092c45d8314998db40c7e11. I wanted to thank you for the PR. Even though it's not merged, the discussion around the implementation was very useful and contributed to the fix. :smile:

**Comment by florianjacob** [comment]
No problem. :smile: I had an exam two days ago and realized I needed more time than expected, so I had to suspend all othe activities in the last two weeks. Sorry!

**Pull request closed without merging**
