### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adelarsq**
Adding installation steps.

### CODE REVIEW

**Comment by jmacdonald** [comment]
Didn't even realize these wiki pages existed. 😄 

I'd honestly prefer to encourage folks to use the [official installation docs](https://amp.rs/docs/installation/). Might be worth adding Ubuntu-specific install instructions [here](https://github.com/jmacdonald/amp/blob/master/documentation/pages/installation.md), if you've identified specific dependencies.

**Comment by adelarsq** [comment]
It's better. I will add the instructions on the official docs.

**Comment by jmacdonald** [comment]
Closing this as the better option is via official docs. :slightly_smiling_face:

**Comment by adelarsq** [comment]
I still didn't have time to do it. I will send a pull request when possible.

**Pull request closed without merging**
